name: Build ICS (manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper (create docs/fide_events.ics)
        run: python scraper/scrape_fide_calendar.py

      - name: Commit ICS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/fide_events.ics
          git commit -m "Add/Update ICS" || echo "No changes"
          git push
